### DENNA FILEN BEHÖVER KONFIGURERAS FÖR PROMETHEUS ####
global:
  scrape_interval: 30s

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
  - job_name: "Appserver 1"
    static_configs:
      - targets: ["13.69.245.26:8000"]

  - job_name: "Appserver 2"
    static_configs:
      - targets: ["13.69.245.168:8000"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["0.0.0.0:9090"]

  - job_name: "load balancer"
    static_configs:
      - targets: ["13.69.245.81:8000"]

  - job_name: "flask"
    static_configs:
    - targets: ["host.docker.internal:8000"]
      labels:
        instance: "flask"
alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]
rule_files:
  - rules.yml