apiVersion: apps/v1
kind: Deployment
metadata:
  name: microblog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microblog
  template:
    metadata:
      labels:
        app: microblog
    spec:
      containers:
        - name: microblog
          image: alexanderwittenby/microblog:v11.3.4
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m
          env:
            - name: FLASK_APP
              value: microblog.py
            - name: FLASK_ENV
              value: production
            - name: SECRET_KEY
              value: my-secret-key
            - name: MYSQL_DATABASE
              value: microblog
            - name: DATABASE_URL
              value: mysql+pymysql://microbloguser:micropassw@mysql:3306/microblog
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 2
