
---
# Here you can add variables that will be available for all hosts.
ansible_python_interpreter: "python3"

region: "{{ vault_azure_region }}" # Change me
resource_group: "{{ vault_azure_resource_group }}" # Change me
domain_name: "{{ vault_domain_name }}" # Change me

admin_email: "{{ vault_admin_email }}"
vmtags:
    StudentId: "{{ vault_student_id }}" # Change me

pub_ssh_key_location: "{{ vault_SSH_public_key_path }}" # Change me, your local ssh key!
server_user: "deploy"
server_user_pass: "{{ vault_server_user_pass }}" # change me
server_user_groups:
    -   sudo


mysql_root_password: "{{ server_user_pass }}"  
mysql_user_password: "{{ server_user_pass }}"

