---
# Here you can add variables that will be available for all hosts.
ansible_python_interpreter: "python3"

region: northeurope
resource_group: DIDA-ALWI22-DV1673-H25-LP2 # Change me
domain_name: alexanderwittenby.me # Change me

admin_email: alwi22@student.bth.se

vmtags:
    StudentId: alwi22 # Change me

pub_ssh_key_location: '/home/alexander/.ssh/azure_video.pub' # Change me, your local ssh key!


server_user: "deploy"
server_user_pass: "test" # change me
server_user_groups:
    -   sudo
