---
-   hosts:
        -   devops
    remote_user: deploy
    become: yes
    become_method: sudo
    roles:
        -   10-first-minutes
    vars_files:
        -   group_vars/all.yml
        -   group_vars/vault.yml
