---
- hosts: monitoring
  become: yes
  become_method: sudo
  remote_user: deploy
  vars_files:
    - group_vars/all.yml
    - group_vars/vault.yml
  roles:
    - install_docker
    - monitoring_instance