name: CD
on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  
  Deploy-to-docker-hub:
    
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.ref_type == 'tag' && github.event.workflow_run_head_branch == 'master' }}  
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checking out the code
        uses: actions/checkout@v4

      - name: Debug workflow context
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Workflow run conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Ref: ${{ github.ref }}"
          echo "Ref type: ${{ github.ref_type }}"
          echo "event.action: ${{ github.event.action }}"
          echo "github.event_name: ${{ github.event_name }}"

      - name: Login to Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}


      - name: Collect Metadata (tags, labels) for Docker image
        id: meta-data
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/microblog
          tags: |
            type=ref,event=tag

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile_prod
          push: true
          tags: ${{ steps.meta-data.outputs.tags }}


      - name: Check if image was pushed
        run: |
          echo "Image pushed with tags: ${{ steps.meta-data.outputs.tags }}"

  deploy-to-servers:
    needs: Deploy-to-docker-hub
    uses: ./.github/workflows/playbook.yml






