name: Deploy microblog application
#test
on:
  workflow_call:
  push:
    branches: [ "master", "feature/ansible-test" ]
  pull_request:
    branches: [ "master", "feature/ansible-test" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
        cache: 'pip'
        cache-dependency-path: requirements/deploy.txt

    - name: Cache Ansible collections
      uses: actions/cache@v3
      with: 
        path: ~/.ansible/collections
        key: ansible-${{ hashFiles('ansible/requirements.yml') }}
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/deploy.txt

    - name: Install Ansible collections
      run: |
        cd ansible && ansible-galaxy collection install -r requirements.yml
    - name: Install dependencies
      run: |
        pip install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements.txt

    - name: Set Azure environment variables
      run: |
        echo '${{ secrets.AZURE_CREDENTIALS }}' > /tmp/azure_creds.json
        echo "AZURE_CLIENT_ID=$(jq -r '.clientId' /tmp/azure_creds.json)" >> $GITHUB_ENV
        echo "AZURE_SECRET=$(jq -r '.clientSecret' /tmp/azure_creds.json)" >> $GITHUB_ENV
        echo "AZURE_TENANT=$(jq -r '.tenantId' /tmp/azure_creds.json)" >> $GITHUB_ENV
        echo "AZURE_SUBSCRIPTION_ID=$(jq -r '.subscriptionId' /tmp/azure_creds.json)" >> $GITHUB_ENV
        rm /tmp/azure_creds.json

    - name: Setup SSH 
      shell: bash
      run: |
        eval `ssh-agent -s`
        mkdir -p /home/runner/.ssh/
        touch /home/runner/.ssh/id_rsa
        echo -e "${{secrets.SSH_PRIVATE_KEY}}" > /home/runner/.ssh/id_rsa
        chmod 700 /home/runner/.ssh/id_rsa

    - name: Run playbook
      run: cd ansible/ && ansible-playbook -i hosts site.yml --private-key=/home/runner/.ssh/id_rsa
      env:
        ANSIBLE_HOST_KEY_CHECKING: "False"
        AZURE_CLIENT_ID: ${{ env.AZURE_CLIENT_ID }}
        AZURE_SECRET: ${{ env.AZURE_SECRET }}
        AZURE_TENANT: ${{ env.AZURE_TENANT }}
        AZURE_SUBSCRIPTION_ID: ${{ env.AZURE_SUBSCRIPTION_ID }}