name: Deploy microblog application

on:
  workflow_call:
  push:
    branches: [ "master" ]
    tags:
      - 'v*.*.*'
  pull_request:
    tags:
      - 'v*.*.*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
        cache: 'pip'
        cache-dependency-path: requirements/deploy.txt

    - name: Cache Ansible collections
      uses: actions/cache@v3
      with: 
        path: ~/.ansible/collections
        key: ansible-${{ hashFiles('ansible/requirements.yml') }}
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/deploy.txt

    - name: Install Ansible collections
      run: |
        cd ansible && ansible-galaxy collection install -r requirements.yml
    - name: Install dependencies
      run: |
        pip install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements.txt

    - name: Setup SSH 
      shell: bash
      run: |
        eval `ssh-agent -s`
        mkdir -p /home/runner/.ssh/
        touch /home/runner/.ssh/id_rsa
        echo -e "${{secrets.SSH_PRIVATE_KEY}}" > /home/runner/.ssh/id_rsa
        chmod 700 /home/runner/.ssh/id_rsa

    - name: Create vault password file
      run: echo "${{ secrets.VAULT_PASSWORD }}" > ansible/.vault_pass
    - name: Get the tag associated with this deployment
      id: get_tag
      run: echo "TAG=${GITHUB_REF#refs/tags/}" 
      
    - name: Run playbook
      run: cd ansible/ && ansible-playbook -i hosts deploy_app.yml --private-key=/home/runner/.ssh/id_rsa --vault-password-file=./.vault_pass
      env:
        ANSIBLE_HOST_KEY_CHECKING: "False"